[package]
name = "Despaux_Noa_WebScraper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.20"
url = "2.5"
thiserror = "1.0"
